### ISSUE TITLE
Dashboard selector switch alignment

### ISSUE THREAD

**Issue by Lyr3x** [flatsiedatsie/domoticz-aurora-theme#50] opened 2018-12-21 12:18 UTC
There is a issue with the alignment of the selector switches and icons. There is a overlapping of the switches and the icons as you can see below:
![image](https://user-images.githubusercontent.com/6078365/50342288-b5490800-0522-11e9-8928-511dbbea8074.png)

**Comment by flatsiedatsie** [comment] 2018-12-21 14:23
There are just too many switches in the first item. Every system has its limits.

**Comment by Lyr3x** [comment] 2018-12-21 14:33
In my opinion there is plenty of unused space.. If the ultra big icons were 50% of the size there is enough space for a second row of buttons. Functionality over design right?

**Comment by flatsiedatsie** [comment] 2019-02-18 13:41
An earlier version actually had a double row design, but it caused problems. It only optically looks like there is enough space. If you dive into the html you will see the problem. The problem is with the ancient html that Domoticz creates.

**Comment by galadril** [comment] 2019-09-04 13:01
It's trucated now correctly... only i don't really like the style of the scrollbar.
should be more in line with the Aurora design right??

![afbeelding](https://user-images.githubusercontent.com/14561640/64256820-7a59f980-cf24-11e9-89a7-8bef8b818b11.png)

![afbeelding](https://user-images.githubusercontent.com/14561640/64256855-8a71d900-cf24-11e9-924f-bbee11400c93.png)

**Comment by Mifidelio** [comment] 2019-09-04 16:19
Firefox : 
![image](https://user-images.githubusercontent.com/33467332/64272751-442a7300-cf40-11e9-9e1d-473feaebda15.png) 
Chrome :
![image](https://user-images.githubusercontent.com/33467332/64272853-7dfb7980-cf40-11e9-9607-68784975edb5.png)

I can propose this but it works only on Chrome and Firefox. If you have ideas...

**Comment by galadril** [comment] 2019-09-04 18:46
Looks goed.. maybe use the color from the theme so it matches the look and feel that they configured?

![image](https://user-images.githubusercontent.com/14561640/64282148-13086d80-cf55-11e9-888e-8081513eb52f.png)

**Comment by Lyr3x** [comment] 2019-09-14 15:39
Switched back to aurora now. Works very good for me. I also agree with galadril, a color from the theme would fit better 👍

**Comment by Mifidelio** [comment] 2019-10-24 22:13
Here the view for Chrome :
![scrollbar](https://user-images.githubusercontent.com/33467332/67529354-31205d80-f6bc-11e9-8e59-c5556b2e20e5.jpg)

**Comment by galadril** [comment] 2019-10-28 08:53
sweet

**Comment by galadril** [comment] 2020-07-31 09:43
Think we can close this issue..

**Closed** 2020-08-01 14:26 UTC
